FROM python:3.10-slim

WORKDIR /app

# ---- System dependencies (important for pyradiomics / simpleitk / numpy builds) ----
RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    g++ \
    git \
    libgl1 \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender1 \
    libffi-dev \
    && rm -rf /var/lib/apt/lists/*

# ---- Python deps ----
COPY requirements.txt .

RUN pip install --no-cache-dir numpy==2.2.6

RUN pip install --no-cache-dir -r requirements.txt

# ---- App code ----
COPY src/ ./src/

# default command
CMD ["python", "src/main.py"]